version: '3.5'
services:
  service:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    command: pm2-docker start ecosystem.config.js
    restart: always
